### ISSUE TITLE
Removal from acknowledgements

### ISSUE THREAD

**Issue by silascutler** [jonathandata1/pegasus_spyware#16]
Please remove my name from the acknowledgements list. I was not asked, nor do I wish to be associated with this project.

**Comment by jonathandata1** [comment]
You were asked, but I will remove you as a reference and you will be archived. ![image](https://user-images.githubusercontent.com/106925/178126304-cc54db72-d4d6-4ffc-9590-36da87a973a6.jpeg)

**Comment by OlivierLaflamme** [comment]
Where's him responding to your question lmfao

**Comment by c3rb3ru5d3d53c** [comment]
> You were asked, but I will remove you as a reference and you will be archived. ![image](https://user-images.githubusercontent.com/106925/178126304-cc54db72-d4d6-4ffc-9590-36da87a973a6.jpeg)

The screenshot is just you asking him if you can give him credit, does not include a reply...

**Comment by jonathandata1** [comment]
take your trolling to twitter please.
